### ISSUE TITLE
false positive ***Blocked File by Keyword***

### ISSUE THREAD

**Issue by fullmetal1** [mancuniancol/script.quasar.btjunkie-mc#3]
log -> http://pastebin.com/raw/iD678GbG

**Comment by fullmetal1** [comment]
Also happens on your rar.bg script and maybe others.

I suspect it's some incorrect regex causing it to look for "3D'" in a way that any filename with '3' and 'd' in it is flagged.

**Comment by mancuniancol** [comment]
I don't see any false positive. You are asking only accept files which one of this words:

[script.quasar.btjunkie-mc] Accepted Keywords: ['480p', 'HDTV', '720p', '1080p', 'CAM', 'TeleSync', ' TS ']

And blocking with one OK this words :
[script.quasar.btjunkie-mc] Blocked Keywords: ['3D', 'Trailer']

For example :
[script.quasar.btjunkie-mc] Dirty Grandpa 2016 Hdrip Xvid Ac3 Evo Torrent ***Blocked File by Keyword***

That file is rejected because of it doesn't have any of the accepted words. 
I don't know if you have read the readme.
Or could you show me a exact example of your claim?

**Comment by mancuniancol** [comment]
OK.. I don't have any feedback from you.  I will close this issue.
